### ISSUE TITLE
Why doesn't the FlatList get the focus?

### ISSUE THREAD

**Issue by CarryHekangkai** [dev-seb/react-native-tv-demo#2]
When I use FlatList instead of ScrollView, the underlayColor set for the Item does not take effect on the TV side, and onFocus is printed with a log
```
import  React, {Component} from 'react';
import {
    StyleSheet,
    View,
    FlatList,
    Text,
    Button,
    Dimensions,
    TouchableHighlight
} from 'react-native';

const { height, width } = Dimensions.get('window');
var ITEM_HEIGHT = 100;

export default class FlatListExample extends Component {

    constructor(props) {
        super(props);
        this.onItemFocus = this.onItemFocus.bind(this);
        this.rowsRef = React.createRef();
        this.state = {
            isFocused : "item_0",
        };
    }

    onItemFocus(key) {
        console.log("onItemFocus:" + key);
        this.setState({
            isFocused : key,
        })
    }

    _renderItem = (item) => { 
        let item1 = item; 
        const key = 'item_' + item1.index;
        var txt = '第' + item1.index + '个'; 
        return ( 
            <TouchableHighlight
              ref={ref => this.rowsRef = ref}
              onPress={()=>{
                console.log("onPress:" + key);
              }}
              onFocus={(e)=>{this.onItemFocus(key)}}
              underlayColor = "#fff"
              style={[
                styles.button,
                // this.state.isFocused === key && styles.buttonBorder
              ]}
              nativeID={key}
              key={key}>
              <Text style={styles.txt}>{txt}</Text>
            </TouchableHighlight>
        ) 
    }
    
    render() { 
        var data = []; 
        for (var i = 0; i < 100; i++) { 
            data.push({ key: i, title: i + '' }); 
        } 
        return ( 
            <View style={{ flex: 1, backgroundColor: "grey" }}> 
                <View style={{ flex: 1 }}> 
                    <FlatList 
                        renderItem={this._renderItem} 
                        numColumns ={4}
                        keyExtractor={(item) => item.key}
                        getItemLayout={(data, index) => ( 
                            { length: ITEM_HEIGHT, offset: (ITEM_HEIGHT + 2) * index, index } 
                        )}
                        data={data}> 
                    </FlatList> 
                </View> 


            </View> 
        ); 
    } 
} 

const styles = StyleSheet.create({ 
    txt: { 
        textAlign: 'center', 
        textAlignVertical: 'center', 
        color: 'white', 
        fontSize: 15, 
    },
    button: {
        width: 80,
        height: 100,
        margin: 5,
        backgroundColor: "blue",
        justifyContent: 'center',
        alignItems: 'center',
    },
    buttonBorder: {
        borderWidth: 10,
        borderColor: 'red',
    },
    buttonFocusedColor: {
        backgroundColor: "#fff",
    }
}); 


module.exports = FlatListExample; 
```

**Comment by dev-seb** [comment]
It seems that React Native doesn't keep the underlay color on focused elements any more.

A simple workaround is to create your own component to manage the focused state and override the backgroundColor style if element has focus :

```javascript
import React, {useState, forwardRef} from 'react';
import {TouchableHighlight} from 'react-native';

const FocusableHighlight = forwardRef((props, ref) => {
  const [focused, setFocused] = useState(false);

  return (
    <TouchableHighlight
      {...props}
      ref={ref}
      onFocus={(event) => {
        setFocused(true);
        if (props.onFocus) {
          props.onFocus(event);
        }
      }}
      onBlur={(event) => {
        setFocused(false);
        if (props.onBlur) {
          props.onBlur(event);
        }
      }}
      style={[
        props.style,
        focused && {
          backgroundColor: props.underlayColor,
        },
      ]}
    />
  );
});

export default FocusableHighlight;
```

Once you have that custom component, just use it instead of TouchableHighlight with the same properties : 

```javascript

import FocusableHighlight from '/path/to/FocusableHighlight.js';

// ...

return ( 
    <FocusableHighlight
      ref={ref => this.rowsRef = ref}
      onPress={()=>{
        console.log("onPress:" + key);
      }}
      onFocus={(e)=>{this.onItemFocus(key)}}
      underlayColor = "#fff"
      style={[
        styles.button,
        // this.state.isFocused === key && styles.buttonBorder
      ]}
      nativeID={key}
      key={key}>
      <Text style={styles.txt}>{txt}</Text>
    </FocusableHighlight>
)
```

**Comment by CarryHekangkai** [comment]
> It seems that React Native doesn't keep the underlay color on focused elements any more.
> 
> A simple workaround is to create your own component to manage the focused state and override the backgroundColor style if element has focus :
> 
> ```js
> import React, {useState, forwardRef} from 'react';
> import {TouchableHighlight} from 'react-native';
> 
> const FocusableHighlight = forwardRef((props, ref) => {
>   const [focused, setFocused] = useState(false);
> 
>   return (
>     <TouchableHighlight
>       {...props}
>       ref={ref}
>       onFocus={(event) => {
>         setFocused(true);
>         if (props.onFocus) {
>           props.onFocus(event);
>         }
>       }}
>       onBlur={(event) => {
>         setFocused(false);
>         if (props.onBlur) {
>           props.onBlur(event);
>         }
>       }}
>       style={[
>         props.style,
>         focused && {
>           backgroundColor: props.underlayColor,
>         },
>       ]}
>     />
>   );
> });
> 
> export default FocusableHighlight;
> ```
> 
> Once you have that custom component, just use it instead of TouchableHighlight with the same properties :
> 
> ```js
> import FocusableHighlight from '/path/to/FocusableHighlight.js';
> 
> // ...
> 
> return ( 
>     <FocusableHighlight
>       ref={ref => this.rowsRef = ref}
>       onPress={()=>{
>         console.log("onPress:" + key);
>       }}
>       onFocus={(e)=>{this.onItemFocus(key)}}
>       underlayColor = "#fff"
>       style={[
>         styles.button,
>         // this.state.isFocused === key && styles.buttonBorder
>       ]}
>       nativeID={key}
>       key={key}>
>       <Text style={styles.txt}>{txt}</Text>
>     </FocusableHighlight>
> )
> ```
Thank you very much for the advice you gave, it helped me a lot.
