### ISSUE TITLE
getting white screen in android tv emulator ...

### ISSUE THREAD

**Issue by divyangmistry** [dev-seb/react-native-tv-demo#3]
![image](https://user-images.githubusercontent.com/16624336/108764153-3cb5ba00-7578-11eb-869d-e6aa11ffe810.png)

getting such error on opening the dev tool ...
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:332:20)
..
what shall I do ... the project won't run !!?

**Comment by CyberCyclone** [comment]
Can you please let me know what you did to solve this? I'm facing the same issue. I had it working for a while but now I'm completely stuck at the white screen.

**Comment by CyberCyclone** [comment]
Figured it out. It happens when the device or simulator drops the internet. Rebooting the simulator fixed it.
